version: '3'
services: 
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./
    ports: 
      - '8081:8081'
      - '3005:3005'
    volumes: 
      - ./:/app
    command: bash ./init.sh